error: introduce new InterventionRequired exception
Future changes will use this type instead of util.Abort for signalling
the user that intervention is required, as in some rebase and histedit
aborts.

--HG--
extra : rebase_source : 455bb76adabeb19407b7d4a4e41e8dd1deaeadd6